/**
 * The label taxonomy the unread reporting groups by.
 *
 * Data only, like the other config modules: no Gmail client and no CLI, so an auditor
 * reading it does not load googleapis. It lived inside list-unread-emails.mjs, which
 * meant a fourth routing taxonomy was defined in a CLI entrypoint while CATEGORIES,
 * ORG_TAGS and COUNTRY_TAGS all lived here.
 *
 * CATEGORY_PRIORITY is ordered: the breakdown files a message under the FIRST of these
 * labels it carries, so a message labeled both Events and Billing reads as Events.
 * TRACKED_LABELS is a flat list for per-label counts and has no ordering meaning.
 */
import {
  LABEL_SENTRY,
  LABEL_KEEP_IMPORTANT,
  LABEL_EVENTS,
  LABEL_EVENTS_MEETUP,
  LABEL_EVENTS_APA,
  LABEL_EVENTS_LUMA,
  LABEL_EVENTS_CALENDAR_NOTIFICATIONS,
  LABEL_EVENTS_PERSONAL,
  LABEL_EVENTS_EVENTBRITE,
  LABEL_EVENTS_IMPORTANT,
  LABEL_MONITORING,
  LABEL_PRODUCT_UPDATES,
  LABEL_PRODUCT_UPDATES_CHATGPT,
  LABEL_PRODUCT_UPDATES_DEV_TOOLS,
  LABEL_PRODUCT_UPDATES_DATA,
  LABEL_COMMUNITIES,
  LABEL_SERVICES,
  LABEL_SERVICES_REAL_ESTATE,
  LABEL_SERVICES_HEALTH,
  LABEL_SERVICES_UTILITIES,
  LABEL_BILLING,
  LABEL_BILLING_CREDIT_MONITORING,
  LABEL_BILLING_MARKET_ALERTS,
  LABEL_BILLING_ACCOUNT_SECURITY,
  LABEL_FORUMS,
  LABEL_FORUMS_LINKEDIN_SOCIAL,
  LABEL_FORUMS_GLASSDOOR,
  LABEL_NEWSLETTERS,
  LABEL_NEWSLETTERS_LINKEDIN,
  LABEL_JOB_SEARCH,
  LABEL_JOB_SEARCH_LINKEDIN,
  LABEL_JOB_SEARCH_GLASSDOOR,
  LABEL_JOB_SEARCH_BACKSTAGE,
  LABEL_JOB_SEARCH_INDEED,
  LABEL_JOB_SEARCH_OTHER,
  LABEL_TRAVEL,
  LABEL_TRAVEL_AIRBNB_RESERVATIONS,
  LABEL_TRAVEL_AIRBNB_SUPPORT,
  LABEL_PROMOTIONS_TRAVEL,
  LABEL_PROMOTIONS_TRAVEL_DISCOUNTS,
  LABEL_ADVOCACY,
  LABEL_ADVOCACY_POLITICAL,
  LABEL_ADVOCACY_NONPROFIT,
  LABEL_TIME_SENSITIVE,
  LABEL_SECURITY_ACCOUNT,
  LABEL_VOICEMAIL,
  LABEL_NETWORKING,
  LABEL_PURCHASES_AMAZON,
  LABEL_PROMOTIONS_RETAIL,
  LABEL_PROMOTIONS_BEAUTY,
  LABEL_PROMOTIONS_FOOD,
  LABEL_PROMOTIONS_FINANCIAL,
  LABEL_AUTOMOTIVE_SHOPPING,
  LABEL_AUTOMOTIVE_INSURANCE,
  LABEL_EVENTS_LOCAL,
  LABEL_EVENTS_PERFORMANCES,
  LABEL_EVENTS_ENTERTAINMENT,
  LABEL_SERVICES_HOME,
  LABEL_BILLING_RECEIPTS,
  LABEL_BILLING_STATEMENTS,
  LABEL_BILLING_INVOICES,
  LABEL_NEWSLETTERS_CIVIC_AUSTIN,
  LABEL_NEWSLETTERS_DEVELOPER,
  LABEL_NEWSLETTERS_NEWS,
  LABEL_NEWSLETTERS_LEGAL,
  LABEL_NEWSLETTERS_PERSONAL_DEV,
  LABEL_EVENTS_DANCE,
  LABEL_ADVOCACY_CCV_BOARD,
  LABEL_PERSONAL_CORRESPONDENCE,
  LABEL_PERSONAL_SELF_CORRESPONDENCE,
  LABEL_LEGAL,
  LABEL_PROMOTIONS,
  LABEL_PROMOTIONS_ENTERTAINMENT,
  LABEL_PROMOTIONS_HEALTH,
  LABEL_PROMOTIONS_TECH,
  LABEL_SERVICES_USPS,
  LABEL_SERVICES_RENTAL_OPS,
  LABEL_PRODUCT_UPDATES_CREDIT_REPORT,
  LABEL_EVENTS_COMMUNITY,
  LABEL_EVENTS_WORKSHOPS,
  LABEL_EVENTS_INVITATIONS,
  LABEL_EVENTS_CONVENTIONS_TECH,
  LABEL_EVENTS_CALENDLY,
  LABEL_EVENTS_TECH,
  LABEL_EVENTS_AI_MONTHLY,
  LABEL_KEEP_REFUNDS,
  LABEL_COMMUNITY_EVENTS,
  LABEL_LINKEDIN_UPDATES,
  LABEL_CALENDLY_NOTIFICATIONS,
  LABEL_DMARC_REPORTS,
  LABEL_MEETING_NOTES,
} from '../lib/constants.mjs';

const CATEGORY_PRIORITY = [
  LABEL_KEEP_IMPORTANT, LABEL_EVENTS, LABEL_MONITORING,
  LABEL_PRODUCT_UPDATES, LABEL_COMMUNITIES, LABEL_SERVICES, LABEL_BILLING,
];

const OTHER_CATEGORY_LABELS = [
  LABEL_FORUMS, LABEL_NEWSLETTERS, LABEL_JOB_SEARCH, LABEL_TRAVEL, LABEL_ADVOCACY,
];

const PRODUCT_UPDATES_SUBLABELS = [
  LABEL_PRODUCT_UPDATES_CHATGPT, LABEL_PRODUCT_UPDATES_CREDIT_REPORT,
  LABEL_PRODUCT_UPDATES_DEV_TOOLS, LABEL_PRODUCT_UPDATES_DATA,
];

const EVENTS_SUBLABELS = [
  LABEL_EVENTS_MEETUP, LABEL_EVENTS_APA, LABEL_EVENTS_LUMA,
  LABEL_EVENTS_CALENDAR_NOTIFICATIONS, LABEL_EVENTS_DANCE,
  LABEL_EVENTS_PERSONAL, LABEL_EVENTS_EVENTBRITE, LABEL_EVENTS_IMPORTANT,
  LABEL_EVENTS_LOCAL, LABEL_EVENTS_PERFORMANCES, LABEL_EVENTS_ENTERTAINMENT,
  LABEL_EVENTS_COMMUNITY, LABEL_EVENTS_WORKSHOPS, LABEL_EVENTS_INVITATIONS,
  LABEL_EVENTS_CONVENTIONS_TECH, LABEL_EVENTS_CALENDLY, LABEL_EVENTS_TECH,
  LABEL_EVENTS_AI_MONTHLY,
];

const KEEP_IMPORTANT_SUBLABELS = [LABEL_KEEP_REFUNDS];

const STANDALONE_LABELS = [
  LABEL_COMMUNITY_EVENTS, LABEL_LINKEDIN_UPDATES,
  LABEL_CALENDLY_NOTIFICATIONS, LABEL_DMARC_REPORTS, LABEL_MEETING_NOTES,
];

const SERVICES_SUBLABELS = [
  LABEL_SERVICES_REAL_ESTATE, LABEL_SERVICES_HEALTH, LABEL_SERVICES_UTILITIES,
  LABEL_SERVICES_HOME, LABEL_SERVICES_USPS, LABEL_SERVICES_RENTAL_OPS,
];

const BILLING_SUBLABELS = [
  LABEL_BILLING_CREDIT_MONITORING, LABEL_BILLING_MARKET_ALERTS, LABEL_BILLING_ACCOUNT_SECURITY,
  LABEL_BILLING_RECEIPTS, LABEL_BILLING_STATEMENTS, LABEL_BILLING_INVOICES,
];

const FORUMS_SUBLABELS = [LABEL_FORUMS_LINKEDIN_SOCIAL, LABEL_FORUMS_GLASSDOOR];

const NEWSLETTERS_SUBLABELS = [
  LABEL_NEWSLETTERS_LINKEDIN, LABEL_NEWSLETTERS_CIVIC_AUSTIN, LABEL_NEWSLETTERS_DEVELOPER,
  LABEL_NEWSLETTERS_NEWS, LABEL_NEWSLETTERS_LEGAL, LABEL_NEWSLETTERS_PERSONAL_DEV,
];

const JOB_SEARCH_SUBLABELS = [
  LABEL_JOB_SEARCH_LINKEDIN, LABEL_JOB_SEARCH_GLASSDOOR, LABEL_JOB_SEARCH_BACKSTAGE,
  LABEL_JOB_SEARCH_INDEED, LABEL_JOB_SEARCH_OTHER,
];

const TRAVEL_SUBLABELS = [LABEL_TRAVEL_AIRBNB_RESERVATIONS, LABEL_TRAVEL_AIRBNB_SUPPORT];

const PROMOTIONS_LABELS = [
  LABEL_PROMOTIONS, LABEL_PROMOTIONS_TRAVEL, LABEL_PROMOTIONS_TRAVEL_DISCOUNTS,
  LABEL_PROMOTIONS_RETAIL, LABEL_PROMOTIONS_BEAUTY, LABEL_PROMOTIONS_FOOD, LABEL_PROMOTIONS_FINANCIAL,
  LABEL_PROMOTIONS_ENTERTAINMENT, LABEL_PROMOTIONS_HEALTH, LABEL_PROMOTIONS_TECH,
];

const ATTENTION_LABELS = [LABEL_TIME_SENSITIVE, LABEL_SECURITY_ACCOUNT, LABEL_VOICEMAIL, LABEL_NETWORKING];

const AUTOMOTIVE_LABELS = [LABEL_AUTOMOTIVE_SHOPPING, LABEL_AUTOMOTIVE_INSURANCE];

const ADVOCACY_SUBLABELS = [LABEL_ADVOCACY_POLITICAL, LABEL_ADVOCACY_NONPROFIT, LABEL_ADVOCACY_CCV_BOARD];

const PERSONAL_LABELS = [LABEL_PERSONAL_CORRESPONDENCE, LABEL_PERSONAL_SELF_CORRESPONDENCE, LABEL_LEGAL];

const TRACKED_LABELS = [
  LABEL_SENTRY, ...CATEGORY_PRIORITY, ...PRODUCT_UPDATES_SUBLABELS, ...EVENTS_SUBLABELS, ...SERVICES_SUBLABELS, ...BILLING_SUBLABELS,
  ...OTHER_CATEGORY_LABELS, ...FORUMS_SUBLABELS, ...NEWSLETTERS_SUBLABELS, ...JOB_SEARCH_SUBLABELS,
  ...TRAVEL_SUBLABELS, ...PROMOTIONS_LABELS, ...ATTENTION_LABELS, ...AUTOMOTIVE_LABELS, ...ADVOCACY_SUBLABELS, ...PERSONAL_LABELS, LABEL_PURCHASES_AMAZON,
  ...KEEP_IMPORTANT_SUBLABELS, ...STANDALONE_LABELS,
];
export { CATEGORY_PRIORITY, TRACKED_LABELS };
